// Static site builder. Run from the perch-store folder:  node tools/build.mjs
// Reads tools/store.config.json + tools/catalog.json + tools/src/*.html and writes the pages and assets/js/config.js.
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const read = (p) => fs.readFileSync(path.join(root, p), 'utf8');
const write = (p, s) => fs.writeFileSync(path.join(root, p), s);

const cfg = JSON.parse(read('tools/store.config.json'));
const catalog = JSON.parse(read('tools/catalog.json'));

// Icons: real Phosphor "regular" files, inlined so they inherit currentColor.
const icon = (name, cls = '') => {
  const svg = read(`tools/icon-${name}.svg`).trim();
  return svg.replace('<svg ', `<svg class="icon ${cls}" aria-hidden="true" focusable="false" width="1em" height="1em" `);
};

// Flatten every product's variants so the cart can look any of them up by id.
const variants = [];
for (const pr of catalog.products) {
  for (const v of pr.variants) {
    variants.push({ ...v, productId: pr.id, name: pr.name, price: pr.price, image: pr.images[0] });
  }
}
catalog.product = { name: cfg.name, products: catalog.products, variants };

const publicConfig = {
  name: cfg.name,
  email: cfg.email,
  currency: cfg.currency,
  locale: cfg.locale,
  shippingFlat: cfg.shippingFlat,
  freeShippingOver: cfg.freeShippingOver,
  deliveryDays: cfg.deliveryDays,
  discounts: cfg.discounts,
  paypalClientId: cfg.paypalClientId,
  orderEndpoint: cfg.orderEndpoint,
};
write(
  'assets/js/config.js',
  `/* Generated by tools/build.mjs. Edit tools/store.config.json and tools/catalog.json instead. */\nwindow.PERCH = ${JSON.stringify({ config: publicConfig, product: catalog.product }, null, 2)};\n`
);

const tokens = {
  name: cfg.name,
  tagline: cfg.tagline,
  email: cfg.email,
  legalName: cfg.legalName,
  legalAddress: cfg.legalAddress,
  vatId: cfg.vatId ? `VAT ID: ${cfg.vatId}` : '',
  deliveryDays: cfg.deliveryDays,
  returnDays: String(cfg.returnDays),
  freeShippingOver: new Intl.NumberFormat(cfg.locale, { style: 'currency', currency: cfg.currency, maximumFractionDigits: 0 }).format(cfg.freeShippingOver),
  shippingFlat: new Intl.NumberFormat(cfg.locale, { style: 'currency', currency: cfg.currency }).format(cfg.shippingFlat),
  year: String(new Date().getFullYear()),
  discount2: String(cfg.discounts.find((d) => d.minQty === 2)?.pct ?? ''),
  discount3: String(cfg.discounts.find((d) => d.minQty === 3)?.pct ?? ''),
  priceFrom: new Intl.NumberFormat(cfg.locale, { style: 'currency', currency: cfg.currency }).format(Math.min(...catalog.products.map((p) => p.price))),
  siteUrl: cfg.siteUrl,
};

const fill = (html) =>
  html
    .replace(/\{\{icon:([a-z-]+)(?::([a-z_-]+))?\}\}/g, (_, n, c) => icon(n, c || ''))
    .replace(/\{\{([A-Za-z0-9]+)\}\}/g, (m, k) => (k in tokens ? tokens[k] : m));

const pages = [
  { file: 'index.html', src: 'index', title: `${cfg.name} | ${cfg.tagline}`, desc: 'Korean-inspired line care: a soft V-line lifting strap and a light posture belt. Free US shipping.', script: 'home', cls: 'page-home', vendor: true },
  { file: 'checkout.html', src: 'checkout', title: `Checkout | ${cfg.name}`, desc: 'Secure checkout.', script: 'checkout', cls: 'page-checkout', noindex: true, minimal: true },
  { file: 'shipping.html', src: 'shipping', title: `Shipping | ${cfg.name}`, desc: 'Delivery times, costs and tracking.', cls: 'page-info' },
  { file: 'returns.html', src: 'returns', title: `Returns | ${cfg.name}`, desc: 'How returns and refunds work.', cls: 'page-info' },
  { file: 'privacy.html', src: 'privacy', title: `Privacy | ${cfg.name}`, desc: 'How we handle your personal data.', cls: 'page-info' },
  { file: 'terms.html', src: 'terms', title: `Terms | ${cfg.name}`, desc: 'Terms of sale.', cls: 'page-info' },
  { file: 'contact.html', src: 'contact', title: `Contact | ${cfg.name}`, desc: 'Questions about an order or a product? Write to us.', cls: 'page-info' },
];

const header = (p) => `
<a class="skip" href="#main">Skip to content</a>
<header class="site-header" data-header>
  <div class="container site-header__row">
    <a class="brand" href="index.html" aria-label="${cfg.name}, home">
      <span class="brand__name">{{name}}</span><span class="brand__ko" lang="ko">선</span>
    </a>
    ${p.minimal ? '' : `<nav class="nav" aria-label="Main">
      <a href="index.html#shop">Shop</a>
      <a href="index.html#ritual">How to wear</a>
      <a href="index.html#faq">FAQ</a>
      <a href="contact.html">Contact</a>
    </nav>`}
    <button class="cart-btn" type="button" data-cart-open aria-label="Open cart, 0 items" aria-haspopup="dialog">
      {{icon:shopping-bag-open}}<span class="cart-btn__label">Cart</span><span class="cart-btn__count" data-cart-count hidden>0</span>
    </button>
  </div>
</header>`;

const drawer = `
<div class="drawer" data-drawer hidden>
  <div class="drawer__scrim" data-cart-close></div>
  <aside class="drawer__panel" role="dialog" aria-modal="true" aria-labelledby="drawer-title" tabindex="-1">
    <div class="drawer__head">
      <h2 id="drawer-title">Your cart</h2>
      <button class="icon-btn" type="button" data-cart-close aria-label="Close cart">{{icon:x}}</button>
    </div>
    <div class="drawer__body" data-drawer-body></div>
    <div class="drawer__foot" data-drawer-foot></div>
  </aside>
</div>
<div class="sr-only" aria-live="polite" data-live></div>`;

const footer = `
<footer class="site-footer">
  <div class="container site-footer__grid">
    <div class="site-footer__brand">
      <a class="brand" href="index.html"><span class="brand__name">{{name}}</span><span class="brand__ko" lang="ko">선</span></a>
      <p>Korean-inspired line care for your face and posture. Shipped free across the US.</p>
    </div>
    <nav aria-label="Shop">
      <h2>Shop</h2>
      <ul>
        <li><a href="index.html#shop">All products</a></li>
        <li><a href="index.html#ritual">How to wear</a></li>
        <li><a href="index.html#faq">FAQ</a></li>
      </ul>
    </nav>
    <nav aria-label="Help">
      <h2>Help</h2>
      <ul>
        <li><a href="shipping.html">Shipping</a></li>
        <li><a href="returns.html">Returns</a></li>
        <li><a href="contact.html">Contact</a></li>
      </ul>
    </nav>
    <nav aria-label="Legal">
      <h2>Legal</h2>
      <ul>
        <li><a href="privacy.html">Privacy</a></li>
        <li><a href="terms.html">Terms of sale</a></li>
      </ul>
    </nav>
  </div>
  <div class="container site-footer__legal">
    <p>&copy; {{year}} {{legalName}}. {{legalAddress}}. {{vatId}}</p>
  </div>
</footer>`;

const layout = (p, body) => `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, viewport-fit=cover, interactive-widget=resizes-content">
<meta name="color-scheme" content="light">
<meta name="theme-color" media="(prefers-color-scheme: light)" content="#fffbf7">
<meta name="theme-color" media="(prefers-color-scheme: dark)" content="#fffbf7">
<title>${p.title}</title>
<meta name="description" content="${p.desc}">
${p.noindex ? '<meta name="robots" content="noindex">' : ''}
<meta property="og:title" content="${p.title}">
<meta property="og:description" content="${p.desc}">
<meta property="og:type" content="website">
<meta property="og:image" content="${cfg.siteUrl ? cfg.siteUrl.replace(/\/$/, '') + '/' : ''}assets/img/og.jpg">
<link rel="icon" href="favicon.svg" type="image/svg+xml">
<link rel="preload" href="assets/fonts/bodoni-latin.woff2" as="font" type="font/woff2" crossorigin>
<link rel="preload" href="assets/fonts/jost-latin.woff2" as="font" type="font/woff2" crossorigin>
<link rel="stylesheet" href="assets/css/style.css">
<script>document.documentElement.classList.add('js')</script>
</head>
<body class="${p.cls}">
${header(p)}
<main id="main">
${body}
</main>
${footer}
${drawer}
<script src="assets/js/config.js"></script>
<script src="assets/js/app.js"></script>
${p.vendor ? '<script src="assets/vendor/gsap.min.js"></script>\n<script src="assets/vendor/ScrollTrigger.min.js"></script>' : ''}
${p.script ? `<script src="assets/js/${p.script}.js"></script>` : ''}
</body>
</html>
`;

for (const p of pages) {
  const body = read(`tools/src/${p.src}.html`);
  write(p.file, fill(layout(p, body)));
}

// Favicon: the Hangul syllable for "line" on blush.
write('favicon.svg', `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 64 64"><rect width="64" height="64" rx="14" fill="#f6dcdf"/><text x="32" y="44" text-anchor="middle" font-family="Apple SD Gothic Neo, Noto Sans KR, sans-serif" font-size="34" font-weight="500" fill="#3a2a2e">선</text></svg>\n`);

console.log(`Built ${pages.length} pages.`);
